# Site settings
baseurl: https://sgeorgiev.netlify.com/
themesDir: ./themes/
languageCode: en
metaDataFormat: yaml
title: Svetlozar Georgiev's portfolio and blog
theme: connoisseur
# Enter your tracking code to enable Google Analytics
googleAnalytics: 
# Disable comments by leaving disqusShortname empty
disqusShortname: Ligh7bringer
disablePathToLower: true
pygmentsstyle: native
RSSLink: feed.xml
paginate: 4

outputs:
  home:
    - HTML
    - RSS

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed

params:
  name: Svetlozar Georgiev
  description: Svetlozar Georgiev's projects, blog posts and other stuff.
  bio: interests...
  email: s.georgiev255\*\*at\*\*gmail
  profile: not.yet
  enableRSS: true
  themeBuilder: true
  favicon: favicon.png # A file located in the static directory
  logo: logo.png # Also located in static directory for logo
  banner: /static/favicon-32x32.png # Used for opengraph
  themeColor: "b30950"

social:
  twitter : https://twitter.com/TO_ADD
  github  : https://github.com/Ligh7bringer
  linkedin: https://www.linkedin.com/in/TO_ADD
  email: s.georgiev255@gmail.com
